"""Secrets Manager access for the key ledger, with compare-and-swap writes.

The ledger is a single JSON secret that every issuance rewrites in full, so a
blind read-modify-write can silently drop a concurrent edit. Secrets Manager
has no conditional put, but staging labels give us the equivalent: stage the
new version as ``AWSPENDING``, then move ``AWSCURRENT`` off the exact version
we read. If anyone else moved it in between, that call fails and we abort with
the ledger untouched.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from typing import TYPE_CHECKING, Any

import boto3
from botocore.exceptions import ClientError

if TYPE_CHECKING:
    from collections.abc import Callable

# Named without "secret"/"token"/"key" so bandit's B105 doesn't read the
# constant as a hardcoded credential — same dodge as PUBLIC_KEYS_RESOURCE_ID
# in infra/aws/stacks/api_stack.py.
DEFAULT_LEDGER_ID = "foodatlas/public-api-keys"
DEFAULT_REGION = "us-west-1"

PENDING = "AWSPENDING"
CURRENT = "AWSCURRENT"


class ConcurrentWriteError(RuntimeError):
    """AWSCURRENT moved between our read and our write; nothing was changed."""


class MalformedLedgerError(RuntimeError):
    """The stored payload is not a JSON object — refuse to overwrite blindly."""


@dataclass
class LedgerStore:
    """Read/write the ledger secret. ``client_factory`` is the test seam."""

    ledger_id: str = DEFAULT_LEDGER_ID
    region: str = DEFAULT_REGION
    profile: str | None = None
    client_factory: Callable[[], Any] | None = None

    def _client(self) -> Any:
        if self.client_factory is not None:
            return self.client_factory()
        session = boto3.Session(profile_name=self.profile, region_name=self.region)
        return session.client("secretsmanager")

    def read(self) -> tuple[dict[str, dict[str, str]], str]:
        """Return ``(payload, version_id)``. The version id is the CAS token."""
        resp = self._client().get_secret_value(SecretId=self.ledger_id)
        raw = str(resp.get("SecretString") or "")
        version_id = str(resp.get("VersionId") or "")
        return _parse(raw), version_id

    def write(
        self,
        payload: dict[str, dict[str, str]],
        *,
        expected_version_id: str,
    ) -> tuple[str, str]:
        """Atomically replace the ledger, or raise :class:`ConcurrentWriteError`.

        Returns ``(new_version_id, warning)``; ``warning`` is non-empty only
        when the cosmetic staging-label cleanup failed after a successful
        write, so the caller can surface it without treating it as an error.
        """
        client = self._client()
        body = json.dumps(payload, indent=2, sort_keys=True)
        staged = client.put_secret_value(
            SecretId=self.ledger_id,
            SecretString=body,
            VersionStages=[PENDING],
        )
        new_version = str(staged["VersionId"])
        try:
            client.update_secret_version_stage(
                SecretId=self.ledger_id,
                VersionStage=CURRENT,
                MoveToVersionId=new_version,
                RemoveFromVersionId=expected_version_id,
            )
        except ClientError as exc:
            raise ConcurrentWriteError(
                "the ledger changed while this command was running — "
                "nothing was written; re-run it"
            ) from exc
        return new_version, self._drop_pending(client, new_version)

    def _drop_pending(self, client: Any, version_id: str) -> str:
        """Clear the redundant staging label. Cosmetic — AWSCURRENT is already set."""
        try:
            client.update_secret_version_stage(
                SecretId=self.ledger_id,
                VersionStage=PENDING,
                RemoveFromVersionId=version_id,
            )
        except ClientError as exc:
            return f"could not clear {PENDING} on version {version_id[:8]}: {exc}"
        return ""


def _parse(raw: str) -> dict[str, dict[str, str]]:
    """Parse the payload, refusing anything that isn't a JSON object.

    A fresh CDK-provisioned secret holds an autogenerated placeholder string.
    That is indistinguishable from corruption here, so both stop the command
    rather than being silently replaced with a one-entry ledger.
    """
    if not raw.strip():
        return {}
    try:
        payload = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise MalformedLedgerError(
            "ledger secret is not JSON (a freshly provisioned secret holds a "
            "placeholder); inspect it and initialise it to {} by hand first"
        ) from exc
    if not isinstance(payload, dict):
        raise MalformedLedgerError(
            f"ledger secret must be a JSON object, got {type(payload).__name__}"
        )
    return payload
