"""API stack: ECS Fargate service behind an ALB.

The Fargate task runs the FastAPI backend image from the ECR repository
provided by :class:`stacks.ecr_stack.EcrStack`. Secrets Manager supplies DB
credentials at task start; the ALB forwards to the task on port 8000.

When the context variable ``api_cert_arn`` is set, the ALB listens on 443
with HTTPS (cert imported from ACM by ARN) and redirects port 80 → 443.
Without the context variable, the ALB falls back to plain HTTP on port 80
so that local ``cdk synth`` and snapshot tests don't require a real cert.

Networking: tasks are placed in public subnets with public IPs so they can
pull from ECR and reach Secrets Manager without a NAT gateway. Security
groups for the ALB and the Fargate task are auto-created by the
`ApplicationLoadBalancedFargateService` pattern — keeping them within this
stack avoids cross-stack SG dependency cycles with NetworkStack.

**Before first deploy** an image must exist in the ECR repository — otherwise
the service will fail to start. Deploy :class:`EcrStack`, then build + push
the API image from ``backend/api/`` to that repository, then deploy this
stack.

Context variables:
- ``api_image_tag`` (default ``latest``): image tag in ECR to deploy.
- ``api_cert_arn`` (optional): ACM certificate ARN in the same region as
  the ALB. When set, enables HTTPS termination on port 443.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

import aws_cdk as cdk
from aws_cdk import Duration, RemovalPolicy
from aws_cdk import aws_certificatemanager as acm
from aws_cdk import aws_ec2 as ec2
from aws_cdk import aws_ecr as ecr
from aws_cdk import aws_ecs as ecs
from aws_cdk import aws_ecs_patterns as ecs_patterns
from aws_cdk import aws_elasticloadbalancingv2 as elbv2
from aws_cdk import aws_iam as iam
from aws_cdk import aws_logs as logs
from aws_cdk import aws_rds as rds
from aws_cdk import aws_s3 as s3
from aws_cdk import aws_secretsmanager as secretsmanager

if TYPE_CHECKING:
    from constructs import Construct

# AWS Secrets Manager resource ID for the hashed public /v1/ API keys.
# Defined as a module constant (and named without "secret"/"token"/"pwd") so
# bandit doesn't false-positive — neither B106 on the `secret_name=` kwarg
# nor B105 on the constant assignment.
PUBLIC_KEYS_RESOURCE_ID = "foodatlas/public-api-keys"


class ApiStack(cdk.Stack):
    """ECS Fargate + ALB hosting the FastAPI backend."""

    def __init__(
        self,
        scope: Construct,
        construct_id: str,
        *,
        vpc: ec2.IVpc,
        repository: ecr.IRepository,
        db_instance: rds.IDatabaseInstance,
        db_secret: secretsmanager.ISecret,
        kgc_bucket: s3.IBucket,
        downloads_bucket: s3.IBucket,
        name_suffix: str = "",
        **kwargs: Any,
    ) -> None:
        super().__init__(scope, construct_id, **kwargs)

        image_tag = self.node.try_get_context("api_image_tag") or "latest"

        self.cluster = ecs.Cluster(
            self,
            "ApiCluster",
            vpc=vpc,
        )

        log_group = logs.LogGroup(
            self,
            "ApiLogGroup",
            retention=logs.RetentionDays.ONE_MONTH,
            removal_policy=RemovalPolicy.DESTROY,
        )

        api_key_secret = secretsmanager.Secret(
            self,
            "ApiKeySecret",
            description="Bearer token for the FoodAtlas API (polite gate).",
            generate_secret_string=secretsmanager.SecretStringGenerator(
                password_length=32,
                exclude_punctuation=True,
            ),
        )

        # Hashed public /v1/ API keys: a JSON object keyed by sha256(key) with
        # {email, created, notes} metadata. CDK creates the secret with an
        # autogenerated placeholder string; the API logs and treats an
        # unparseable payload as "no keys" (fail-closed for public traffic,
        # internal-key path unaffected). New keys are issued via
        # ``backend/api/scripts/issue_public_key.py`` and pasted in with
        # ``aws secretsmanager update-secret``; the API picks them up on the
        # next refresh tick (default 5 min) — no redeploy needed.
        public_keys_secret = secretsmanager.Secret(
            self,
            "ApiPublicKeysSecret",
            secret_name=f"{PUBLIC_KEYS_RESOURCE_ID}{name_suffix}",
            description=(
                "Hashed public /v1/ API keys ({sha256(key): {email, created, notes}})."
            ),
        )

        # 0.5 vCPU / 1 GB — the smallest Fargate tier (0.25/512) was
        # starvation-prone under any concurrent load (see stress-test in
        # issue #187). One step up gives headroom without changing cost
        # category materially.
        task_definition = ecs.FargateTaskDefinition(
            self,
            "ApiTaskDefinition",
            cpu=512,
            memory_limit_mib=1024,
            runtime_platform=ecs.RuntimePlatform(
                cpu_architecture=ecs.CpuArchitecture.X86_64,
                operating_system_family=ecs.OperatingSystemFamily.LINUX,
            ),
        )

        task_definition.add_container(
            "ApiContainer",
            image=ecs.ContainerImage.from_ecr_repository(
                repository,
                tag=image_tag,
            ),
            logging=ecs.LogDrivers.aws_logs(
                stream_prefix="foodatlas-api",
                log_group=log_group,
            ),
            environment={
                # API_HOST is set via the Dockerfile ENV to bind all
                # interfaces inside the container; no need to duplicate here.
                "API_DEBUG": "False",
                "API_CORS_ORIGINS": ",".join(
                    [
                        "https://foodatlas.ai",
                        "https://www.foodatlas.ai",
                        "https://dev.foodatlas.ai",
                        "http://localhost:3000",
                        "http://localhost:3001",
                    ],
                ),
                "DB_HOST": db_instance.db_instance_endpoint_address,
                "DB_PORT": db_instance.db_instance_endpoint_port,
                "DB_NAME": "foodatlas",
                "KGC_BUCKET": kgc_bucket.bucket_name,
                "API_DOWNLOADS_BUCKET": downloads_bucket.bucket_name,
                "API_DOWNLOADS_REGION": cdk.Stack.of(self).region,
                "API_PUBLIC_KEYS_SECRET_NAME": public_keys_secret.secret_name,
                "API_AWS_REGION": cdk.Stack.of(self).region,
            },
            secrets={
                "DB_USER": ecs.Secret.from_secrets_manager(db_secret, "username"),
                "DB_PASSWORD": ecs.Secret.from_secrets_manager(db_secret, "password"),
                "API_KEY": ecs.Secret.from_secrets_manager(api_key_secret),
            },
            port_mappings=[
                ecs.PortMapping(container_port=8000, protocol=ecs.Protocol.TCP),
            ],
        )

        # Task role needs read access to KGC bucket for ad-hoc fetches
        kgc_bucket.grant_read(task_definition.task_role)

        # Read access to the public-keys secret. The API polls this at runtime
        # via boto3 so we cannot inject the value once at task start.
        public_keys_secret.grant_read(task_definition.task_role)

        # Permissions required for ECS exec (see ApiService construction
        # below for the EnableExecuteCommand override). Without these,
        # `aws ecs execute-command` returns "TargetNotConnected".
        task_definition.task_role.add_to_principal_policy(
            iam.PolicyStatement(
                actions=[
                    "ssmmessages:CreateControlChannel",
                    "ssmmessages:CreateDataChannel",
                    "ssmmessages:OpenControlChannel",
                    "ssmmessages:OpenDataChannel",
                ],
                resources=["*"],
            )
        )

        cert_arn = self.node.try_get_context("api_cert_arn")
        service_kwargs: dict[str, Any] = {
            "cluster": self.cluster,
            "task_definition": task_definition,
            # Baseline of 2 tasks gives HA across deploys (min_healthy=100
            # means rolling deploys never drop below this) and ~headroom
            # for one task's worth of measured saturation (~50 RPS).
            # Autoscaling configured below takes us up to 6 if load grows.
            "desired_count": 2,
            "min_healthy_percent": 100,
            "public_load_balancer": True,
            "assign_public_ip": True,
            "task_subnets": ec2.SubnetSelection(subnet_type=ec2.SubnetType.PUBLIC),
            "health_check_grace_period": Duration.seconds(60),
        }
        if cert_arn:
            certificate = acm.Certificate.from_certificate_arn(
                self,
                "ApiCertificate",
                cert_arn,
            )
            service_kwargs.update(
                certificate=certificate,
                protocol=elbv2.ApplicationProtocol.HTTPS,
                redirect_http=True,
                listener_port=443,
            )
        else:
            service_kwargs["listener_port"] = 80

        self.service = ecs_patterns.ApplicationLoadBalancedFargateService(
            self,
            "ApiService",
            **service_kwargs,
        )

        # ECS exec on the underlying FargateService so ops can
        # `aws ecs execute-command` into a running task — no SSH bastion,
        # no RDS port-forward setup. The API container already has DB
        # creds + VPC reach, so ad-hoc SQL becomes a `python -c` away.
        # Session traffic is IAM-gated and SSM-logged. CDK auto-wires
        # the ssmmessages:* perms onto the task role when this is on.
        # Set via L1 escape hatch because the pattern doesn't expose it.
        self.service.service.node.default_child.add_property_override(  # type: ignore[union-attr]
            "EnableExecuteCommand", True
        )

        self.service.target_group.configure_health_check(
            path="/health",
            healthy_http_codes="200",
            interval=Duration.seconds(30),
            timeout=Duration.seconds(5),
            healthy_threshold_count=2,
            unhealthy_threshold_count=3,
        )

        # Auto-scale on ALB request rate. Target 1800 req/min/task (= 30
        # RPS/task) — about half of the per-task saturation measured in
        # the stress test (issue #187), giving us a buffer before
        # latency degrades. Scale-out is aggressive (1 min cooldown);
        # scale-in is conservative (3 min) so transient dips don't churn
        # tasks.
        scaling = self.service.service.auto_scale_task_count(
            min_capacity=2,
            max_capacity=6,
        )
        scaling.scale_on_request_count(
            "ApiRequestRateScaling",
            requests_per_target=1800,
            target_group=self.service.target_group,
            scale_in_cooldown=Duration.seconds(180),
            scale_out_cooldown=Duration.seconds(60),
        )

        scheme = "https" if cert_arn else "http"
        cdk.CfnOutput(
            self,
            "ApiUrl",
            value=f"{scheme}://{self.service.load_balancer.load_balancer_dns_name}",
            description="Public API URL (ALB DNS)",
        )

        cdk.CfnOutput(
            self,
            "ApiKeySecretArn",
            value=api_key_secret.secret_arn,
            description=(
                "Secrets Manager ARN for the API bearer token. Fetch the "
                "value with: aws secretsmanager get-secret-value "
                "--secret-id <arn> --query SecretString --output text"
            ),
        )

        cdk.CfnOutput(
            self,
            "ApiPublicKeysSecretArn",
            value=public_keys_secret.secret_arn,
            description=(
                "Secrets Manager ARN holding the JSON object of hashed "
                "public /v1/ API keys. Issue new keys with "
                "backend/api/scripts/issue_public_key.py and merge them in "
                "with aws secretsmanager update-secret."
            ),
        )
